#pragma once

#define PV_KEYBOARD_KEY_A	0x41
#define PV_KEYBOARD_KEY_B	0x42
#define PV_KEYBOARD_KEY_C	0x43
#define PV_KEYBOARD_KEY_D	0x44
#define PV_KEYBOARD_KEY_E	0x45
#define PV_KEYBOARD_KEY_F	0x46
#define PV_KEYBOARD_KEY_G	0x47
#define PV_KEYBOARD_KEY_H	0x48
#define PV_KEYBOARD_KEY_I	0x49
#define PV_KEYBOARD_KEY_J	0x4A
#define PV_KEYBOARD_KEY_K	0x4B
#define PV_KEYBOARD_KEY_L	0x4C
#define PV_KEYBOARD_KEY_M	0x4D
#define PV_KEYBOARD_KEY_N	0x4E
#define PV_KEYBOARD_KEY_O	0x4F
#define PV_KEYBOARD_KEY_P	0x50
#define PV_KEYBOARD_KEY_Q	0x51
#define PV_KEYBOARD_KEY_R	0x52
#define PV_KEYBOARD_KEY_S	0x53
#define PV_KEYBOARD_KEY_T	0x54
#define PV_KEYBOARD_KEY_U	0x55
#define PV_KEYBOARD_KEY_V	0x56
#define PV_KEYBOARD_KEY_W	0x57
#define PV_KEYBOARD_KEY_X	0x58
#define PV_KEYBOARD_KEY_Y	0x59
#define PV_KEYBOARD_KEY_Z	0x5A

#define PV_KEYBOARD_KEY_LEFT	0x25
#define PV_KEYBOARD_KEY_UP		0x26
#define PV_KEYBOARD_KEY_RIGHT	0x27
#define PV_KEYBOARD_KEY_DOWN	0x28

#define PV_KEYBOARD_KEY_BACKSPACE	0x08
#define PV_KEYBOARD_KEY_TAB			0x09
#define PV_KEYBOARD_KEY_ENTER		0x0D
#define PV_KEYBOARD_KEY_ESCAPE		0x1B
#define PV_KEYBOARD_KEY_SPACE		0x20
#define PV_KEYBOARD_KEY_PAGEUP		0x21
#define PV_KEYBOARD_KEY_PAGEDOWN	0x22
#define PV_KEYBOARD_KEY_END			0x23
#define PV_KEYBOARD_KEY_HOME		0x24
#define PV_KEYBOARD_KEY_INSERT		0x2D
#define PV_KEYBOARD_KEY_DELETE		0x2E
