#pragma once

#if defined(PV_WINDOWING_API_GLFW)
	#define PV_MOUSE_BUTTON_1         0
	#define PV_MOUSE_BUTTON_2         1
	#define PV_MOUSE_BUTTON_3         2
	#define PV_MOUSE_BUTTON_4         3
	#define PV_MOUSE_BUTTON_5         4
	#define PV_MOUSE_BUTTON_LEFT      PV_MOUSE_BUTTON_1
	#define PV_MOUSE_BUTTON_RIGHT     PV_MOUSE_BUTTON_2
	#define PV_MOUSE_BUTTON_MIDDLE    PV_MOUSE_BUTTON_3
	#define PV_MOUSE_BUTTON_THUMB1    PV_MOUSE_BUTTON_4
	#define PV_MOUSE_BUTTON_THUMB2    PV_MOUSE_BUTTON_5
#elif defined(PV_WINDOWING_API_WIN32)
	#define PV_MOUSE_BUTTON_LEFT	0x00
	#define PV_MOUSE_BUTTON_RIGHT	0x01
	#define PV_MOUSE_BUTTON_MIDDLE	0x02
	#define PV_MOUSE_BUTTON_THUMB1	0x03
	#define PV_MOUSE_BUTTON_THUMB2	0x04
	#define PV_MOUSE_BUTTON_1		0x00
	#define PV_MOUSE_BUTTON_2		0x01
	#define PV_MOUSE_BUTTON_3		0x02
	#define PV_MOUSE_BUTTON_4		0x03
	#define PV_MOUSE_BUTTON_5		0x04
#endif
